version: '2'
services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    links:
      - "middleware"
    restart: always
    volumes:
      - ./src:/code
    environment:
      IDENTIFIER: frontend
  middleware:
    build: .
    links:
      - "backend"
    restart: always
    environment:
      IDENTIFIER: middleware
  backend:
    build: .
    restart: always
    environment:
      IDENTIFIER: backend
